cat:
	cat Makefile

p1:
	./part1.py

p2:
	pypy ./part2.py

mypy:
	mypy --config-file mypy.ini .

dot1:
	dot -T jpg graph_example.dot -o graph_example.jpg

dot2:
	dot -T jpg graph_example2.dot -o graph_example2.jpg

doti:
	dot -T jpg graph_input.dot -o graph_input.jpg
